### ISSUE TITLE
It's not working for me in rails 7.0.4

### ISSUE THREAD

**Issue by DebakeDSP94** [arielj/vanilla-nested#65]
It is putting the link text on the page, but does not add a nested form field when clicked.  I am getting this error in the console.
vanilla_nested.js:16 Uncaught TypeError: Cannot read properties of null (reading 'insertAdjacentHTML')
    at window.addVanillaNestedFields (vanilla_nested.js:16:19)
    at HTMLDocument.<anonymous> (vanilla_nested.js:154:9)
window.addVanillaNestedFields @ vanilla_nested.js:16
(anonymous) @ vanilla_nested.js:154

I'm not sure if I'm doing the right thing by putting this here, but I thought it might be important.  If I'm just doing something wrong, then please disregard.  Please let me know if you need any more information.  Thank you.

**Comment by arielj** [comment]
What's the setup? it seems to be failing to find the container where the fields should be added. Make sure you are passing a correct css selector as the third argument for the link_to_add_nested helper https://github.com/arielj/vanilla-nested#addingremoving-nested-fields (check the example there, it is `#order-items` because there's a div with id `order-items`)

**Comment by DebakeDSP94** [comment]
Thank you so much. That fixed it for me.  It was throwing me off, in that I was thinking that was the text to appear on the link, rather than an id to tell it which div to target.  It's working now.
